const ERROR_CODES = {
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DUPLICATE_BOARD_MEMBER: 'DUPLICATE_BOARD_MEMBER',
  INVALID_TASK_POSITION: 'INVALID_TASK_POSITION',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT'
};

const TASK_STATUS = ['Backlog', 'Todo', 'In Progress', 'Review', 'Blocked', 'Done'];
const TASK_PRIORITIES = ['Low', 'Medium', 'High', 'Urgent'];
const CONTEXT_TYPES = ['work', 'personal', 'study', 'health', 'finance', 'family', 'other'];

const ACTIVITY_ACTIONS = [
  'TASK_CREATED',
  'TASK_UPDATED',
  'TASK_MOVED',
  'TASK_DELETED',
  'COMMENT_ADDED',
  'COMMENT_DELETED',
  'MEMBER_ADDED',
  'MEMBER_REMOVED'
];

module.exports = {
  ERROR_CODES,
  TASK_STATUS,
  TASK_PRIORITIES,
  CONTEXT_TYPES,
  ACTIVITY_ACTIONS
};
